[package]
name = "thrustwork"
version = "0.1.0"
edition = "2024"

[dependencies]
automerge = "0.7"
autosurgeon = "0.10.0"
clap = { version = "4.5.53", features = ["derive"] }
#samod = { version = "0.5", features = ["tokio", "tungstenite"] }
samod = { path = "/home/alex/Projects/automerge/samod/samod", features = ["tokio", "tungstenite"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.27", features = ["native-tls"] }

[dev-dependencies]
tempfile = "3.23.0"
